# Generated by Django 3.2.6 on 2021-09-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
