# Generated by Django 3.2.6 on 2021-09-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_auto_20210915_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hash_tag',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
