# Generated by Django 3.2.6 on 2021-09-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_alter_post_hash_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='variety',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
