# Generated by Django 3.2.6 on 2021-09-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0010_auto_20210928_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='위치', max_length=20),
        ),
    ]
