# Generated by Django 3.2.6 on 2021-10-01 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0011_post_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 10, 48, 36, 359207, tzinfo=utc), verbose_name='data published'),
        ),
    ]
