# Generated by Django 3.2.6 on 2021-09-30 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0012_auto_20210930_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 8, 23, 35, 881473, tzinfo=utc), verbose_name='data published'),
        ),
    ]
